main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('contactskill/', views.contactskill, name='contactskill'),
    path('experience/', views.experience, name='experience'),
    path('works/', views.works, name='works'),
    path('story1/', views.story1, name='story1'),
]

story4/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),),
    path('story5/',include('story5.urls'), name='story5'),
    path('story6/',include('story6.urls'), name='story6'),
]

story6/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.allactivities, name='allactivities'),
    path('addactivities/', views.addactivities, name='addactivities'),
    path('addparticipant/P<int:ppl_id>/', views.addparticipant, name='addparticipant'),
]

story6/models.py
from django.db import models

# Create your models here.

class Activities(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class People(models.Model):
    participant = models.CharField(max_length=50)
    activities = models.ForeignKey(Activities, on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return self.participant

story6/forms.py
from django import forms
from .models import Activities, People

class FormActivities(forms.Form):
    class Meta:
        model = Activities
        fields = ['name']
        widgets ={
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
        }

    error_messages = {
        'required' : 'Please input text'
    }

    name = forms.CharField(
        label='Activity Name :', required=True,
        max_length=100,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert activity name'}))

class FormPeople(forms.Form):
    class Meta:
        model = People
        fields = ['participant']
        widgets ={
            'participant' : forms.TextInput(attrs={'class': 'form-control'}),
        }

    error_messages = {
        'required' : 'Please input text'
    }

    participant = forms.CharField(
        label='Name :', required=True,
        max_length=50,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert your name'}))

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import FormActivities, FormPeople
from .models import People,Activities

# Create your views here.

def allactivities(request):
    activities = Activities.objects.all()
    people = People.objects.all()
    context = {
        'page_title':'All Activities',
        'activities':activities,
        'people':people,
    }
    return render(request, 'allactivities.html',context) 

def addactivities(request):
    form_activities = FormActivities(request.POST or None)
    if request.method == 'POST':
        if form_activities.is_valid():
            Activities.objects.create(
                name = form_activities.cleaned_data['name'],
            )
            return redirect("/story6/")
        else:
            return render(request, 'addactivities.html', {'form_activities':form_activities, 'status':'failed'})
    else:
        return render(request, 'addactivities.html', {'form_activities':form_activities})

def addparticipant(request, ppl_id):
    form_participant = FormPeople(request.POST or None)
    if request.method == 'POST':
        if form_participant.is_valid():
            People.objects.create(
                participant = form_participant.cleaned_data['participant'],
                activities = Activities.objects.get(id = ppl_id)
            )
            return redirect("/story6/")
        else:
            return render(request,'addparticipant.html', {'form_participant':form_participant, 'status':'failed'})
    else:
        return render(request, 'addparticipant.html', {'form_participant':form_participant})

story6/templates/addactivities.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Add Activity
        </title>
    </head>
    <body>
        <div class="container" style="overflow-wrap: break-word; text-align: center; margin-top: 5%;">
            <!-- buat ngamanin data dan enskripsi -->  
            <h1>Add Activity</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <table class="table-responsive-md" style="width:100%; margin-top: 2%;">
                {{ form_activities.as_table }}
                </table>
                <button type="submit" value="Add" class="btn btn-success" style="margin-top: 2%;">Submit</button>
            </form>
            <a class="btn btn-info" style="margin-top: 2%;" href="{% url 'story6:allactivities' %}">See All Activities</a>
        </div>
    </body>
</html>
{% endblock content %}

story6/templates/addparticipant.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Add Participant
        </title>
        <style>
            th{
                font-size: 3.5vh;
            }
        </style>
    </head>
    <body>
        <div class="container" style="overflow-wrap: break-word; text-align: center; margin-top: 5%;">
            <!-- buat ngamanin data dan enskripsi -->  
            <h1>Add Participant</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <table class="table-responsive-md" style="width:100%; margin-top: 2%;">
                {{ form_participant.as_table }}
                </table>
                <button type="submit" value="Add" class="btn btn-success" style="margin-top: 2%;">Submit</button>
            </form>
            <a class="btn btn-info" style="margin-top: 2%;" href="{% url 'story6:allactivities' %}">See All Activities</a>
        </div>
    </body>
</html>
{% endblock content %}

story6/templates/allactivities.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            All Activities
        </title>
    </head>
    <body>
        <div class="container" style="align-self: center; width: 100%; overflow-wrap: break-word; text-align: center; margin-top: 5%;">
            <h1>Activities</h1>
            <div class="flex-container" style="width: 50%; display: flex; margin-left: 25%;">
                <!-- col-centered untuk ngecenter table, dalam kasus home tombolnya mau di center-->
                {% for a in activities %}
                <div class="col-centered" style="border: medium solid orangered; margin-right: 2%; margin-left: 2%;">
                    <p><b>{{ a.name }}</b></p>
                    {% for p in people %}
                    {% if p.activities == a %}
                    <div class="col-centered">
                        {{ p.participant }}
                    </div>
                {% endif %}
                {% endfor %}
                <div>
                    <a class="btn btn-warning" href="{% url 'story6:addparticipant' ppl_id=a.id %}">Join Activity</a>
                </div>
                </div>
                {% endfor %}
            </div>
            </table>
            <a class="btn btn-info" style="margin-top: 2%;" href="{% url 'story6:addactivities' %}">Add New Activity</a>
    </body>
</html>
{% endblock content %}