main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('contactskill/', views.contactskill, name='contactskill'),
    path('experience/', views.experience, name='experience'),
    path('works/', views.works, name='works'),
    path('story1/', views.story1, name='story1'),
]

story4/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),),
    path('story5/',include('story5.urls'), name='story5'),
    path('story6/',include('story6.urls'), name='story6'),
]

story5/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coursedetail/P<int:detail_id>/', views.coursedetail, name='coursedetail'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('', views.courseadd, name='courseadd'),
    path('courseadded/', views.courseadded, name='courseadded'),
]

story5/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=50)
    sks = models.IntegerField()
    desc = models.TextField(max_length=200)
    term = models.CharField(max_length=15)
    place = models.CharField(max_length=30)

    def __str__(self):
        return "{}. {}".format(self.id, self.name)

story5/forms.py
from django import forms
from .models import Course

class FormCourse(forms.Form):
    class Meta:
        model = Course
        fields = ['name', 'lecturer','sks','desc','term','place']
        widgets ={
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'lecturer' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'desc' : forms.Select(attrs={'class': 'form-control'}),
            'term' : forms.Select(attrs={'class': 'form-control'}),
            'place' : forms.TextInput(attrs={'class': 'form-control'}),
        }

    error_messages = {
        'required' : 'Please input text'
    }

    name = forms.CharField(
        label='Course Name :', required=True,
        max_length=50,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert course name'}))

    lecturer = forms.CharField(
        label='Lecturer :', required=True,
        max_length=50,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert lecturer name'}))

    sks = forms.IntegerField(
        label='Number of Credits :', required=True,
        widget=forms.NumberInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert credits of this course'}))

    desc = forms.CharField(
        label='Description :', required=True,
        max_length=200,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Write all about this course'}))

    term = forms.CharField(
        label='Term and Year :', required=True,
        max_length=15,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Insert term and year (ex : Gasal 2019/2020)'}))

    place = forms.CharField(
        label='Location :', required=True,
        max_length=30,
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'type' : 'text',
            'placeholder' : 'Where this class take place'}))

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import FormCourse
from .models import Course

# Create your views here.
def coursedetail(request, detail_id):
    try:
        course_detail = Course.objects.get(id=detail_id)
        context = {
            'course':course_detail
        }
        return render(request, 'coursedetail.html', context)
    except:
        return redirect('/story5/courseadded')

def delete(request, delete_id):
    Course.objects.filter(id=delete_id).delete()
    return redirect('story5:courseadded')

def courseadded(request):
    courses = Course.objects.all()
    context = {
        'page_title':'All Schedule',
        'courses':courses
    }
    return render(request, 'courseadded.html',context)       

def courseadd(request):
    form_course = FormCourse(request.POST or None)
    if request.method == 'POST':
        if form_course.is_valid():
            Course.objects.create(
                name = form_course.cleaned_data['name'],
                lecturer = form_course.cleaned_data['lecturer'],
                sks = form_course.cleaned_data['sks'],
                desc = form_course.cleaned_data['desc'],
                term = form_course.cleaned_data['term'],
                place = form_course.cleaned_data['place']
            )
            return HttpResponseRedirect("/story5/courseadded")
    context = {
        'page_title':'Create Schedule',
        'form_course':form_course
    }
    return render(request, 'courseadd.html',context)

story5/templates/courseadd.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Add Course to Schedule
        </title>
    </head>
    <body>
        <div class="container" style="overflow-wrap: break-word; text-align: center; margin-top: 5%;">
            <!-- buat ngamanin data dan enskripsi -->
            {% csrf_token %}    
            <h1>Add Course Schedule</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <table class="table-responsive-md" style="width:100%; margin-top: 2%;">
                {{ form_course.as_table }}
                </table>
                <button type="submit" value="Add" class="btn btn-success" style="margin-top: 2%;">Submit</button>
            </form>
            <a class="btn btn-info" style="margin-top: 2%;" href="{% url 'story5:courseadded' %}">See Schedule</a>
        </div>
    </body>
</html>
{% endblock content %}

story5/templates/courseadded.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Schedule
        </title>
        <style>
            th{
                font-size: 3.5vh;
            }
        </style>
    </head>
    <body>
        <div class="container" style="align-self: center; width: 100%; overflow-wrap: break-word; text-align: center; margin-top: 5%;">
            <h1>Schedule</h1>
            <table class="table-responsive-md" style="width: 100%; margin-top: 3%;">
            <tr>
                <th>
                    Course Name
                </th>
                <th>
                    Lecturer
                </th>
                <th>
                    Room
                </th>
            </tr>
            {% for c in courses %}
            <tr>
                <td>
                    {{c.name}}
                </td>
                <td>
                    {{c.lecturer}}
                </td>
                <td>
                    {{c.place}}
                </td>
                <td>
                    <a class="btn btn-warning" href="{% url 'story5:coursedetail' detail_id=c.id %}">Details</a>
                </td>
                <td>
                    <a class="btn btn-danger" href="{% url 'story5:delete' delete_id=c.id %}">Delete</a>
                </td>
            </tr>
                {% endfor %}
            </table>
            <a class="btn btn-info" style="margin-top: 2%;" href="{% url 'story5:courseadd' %}">Add Course to Schedule</a>
    </body>
</html>
{% endblock content %}

story5/templates/coursedetail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Course Detail
        </title>
    </head>
    <body>
        <div class="container" style="align-self: center; width: 100%; overflow-wrap: break-word; text-align: center; margin-top: 5%;">
        <table class="table-responsive-md" style="width: 100%;">
            <tr>
                <th>
                    Course Name
                </th>
                <th>
                    Lecturer
                </th>
                <th>
                    Description
                </th>
                <th>
                    Credits
                </th>
                <th>
                    Term
                </th>
                <th>
                    Room
                </th>
            </tr>
            <tr>
                <td>
                    {{course.name}}
                </td>
                <td>
                    {{course.lecturer}}
                </td>
                <td>
                    {{course.desc}}
                </td>
                <td>
                    {{course.sks}}
                </td>
                <td>
                    {{course.term}}
                </td>
                <td>
                    {{course.place}}
                </td>
            </tr>
        </table>
        <a href="{% url 'story5:courseadded' %}">
            <button class="btn btn-icon btn-danger" style="margin-top: 2%;">Back to Schedule</button>
        </a>
        </div>
    </body>
</html>
{% endblock content %}