main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('contactskill/', views.contactskill, name='contactskill'),
    path('experience/', views.experience, name='experience'),
    path('works/', views.works, name='works'),
    path('story1/', views.story1, name='story1'),
]

story4/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),),
    path('story5/',include('story5.urls'), name='story5'),
    path('story6/',include('story6.urls'), name='story6'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Caladea&family=Calistoga&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@600&family=Prata&display=swap" rel="stylesheet">
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <header>
      <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:home' %}"> Story 2 Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:aboutme' %}">About Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:experience' %}">Experience</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:works' %}">Works</a>
            </li>
          </ul>
        </div>
        </nav>
  </header>
  </body>
  {% block content %}
  {% endblock content %}
</html>