main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('contactskill/', views.contactskill, name='contactskill'),
    path('experience/', views.experience, name='experience'),
    path('works/', views.works, name='works'),
    path('story1/', views.story1, name='story1'),
]

story4/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'),),
    path('story5/',include('story5.urls'), name='story5'),
    path('story6/',include('story6.urls'), name='story6'),
]

story5/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coursedetail/P<int:detail_id>/', views.coursedetail, name='coursedetail'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('', views.courseadd, name='courseadd'),
    path('courseadded/', views.courseadded, name='courseadded'),
]

story6/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.allactivities, name='allactivities'),
    path('addactivities/', views.addactivities, name='addactivities'),
    path('addparticipant/P<int:ppl_id>/', views.addparticipant, name='addparticipant'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'main/home.html')

def aboutme(request):
    return render(request, 'main/aboutme.html')

def contactskill(request):
    return render(request, 'main/contactskill.html')

def experience(request):
    return render(request, 'main/experience.html')

def works(request):
    return render(request, 'main/works.html')

def story1(request):
    return render(request, 'main/story1.html')

main/templates/main/aboutme.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            About Me
        </title>
    </head>
    <body class="styles">
        <div class="container">
            <div class="flex-container" style="align-content: center; width: 100%; display: flex; float: left; margin-top: 8vh; overflow-wrap: break-word;">
                <div style="width: 100%;">
                    <img src="{% static 'MY22square.jpg' %}" width="300" height="300" class="img-fluid rounded-circle"><br/>
                    <a href="{% url 'main:contactskill' %}" style="margin-top: 5vh;" class="buttons btn btn-warning" role="button"><b>Skills and Contacts</b></a>
                </div>
                <div style="text-align: left; width: 100%;">
                    <h1>Herbiyona</h1>
                    <h2>Information System Student</h2>
                    <h3 style="max-width: 85%;">
                        Hello! My name is Herbiyona. You can call me Yona. I am currently in my second years of studying Informations Systems at Faculty of Computer Science, Universitas Indonesia. I really like to write and read. I also love to interact with new people so it’s not a big problem for me to fit in. I am a detail-oriented person and able to work in team.
                    </h3>
                </div>
            </div>
        </div>
        <div class="shape1me"></div>
        <div class="shape2me"></div>
        <div class="shape3me"></div>
    </body>
</html>
{% endblock content %}

main/templates/main/contactskill.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Contacts and Skills
        </title>
    </head>
    <body class="styles">
        <div class="container" style="overflow-wrap: break-word;">
            <h1 style="margin-top: 8vh;">Skills</h1>
            <h3 style="text-align: center; margin-top: 5vh; word-spacing: 3vw;">copywriting java python photoshop proofreading</h3>
            <h1 style="margin-top: 8vh;">Contacts</h1>
            <div class="flex-container" style="width: 100%; display: flex; float: left; font-size: 2.5vw;">
                <div style="margin-right: auto; margin-left: auto; padding: 2%;">
                    <a href="https://www.linkedin.com/in/herbiyona-h-a192531b3/" target="_blank">LinkedIn</a>
                </div>
                <div style="margin-right: auto; margin-left: auto; padding: 2%;">
                    <a href="https://instagram.com/herbiyona_" target="_blank">Instagram</a>
                </div>
                <div style="margin-right: auto; margin-left: auto; padding: 2%;">
                    <a href="https://gitlab.com/herbiyona" target="_blank">GitLab</a>
                </div>
            </div>
        </div>
        <div class="shape1cs"></div>
        <div class="shape2cs"></div>
        <div class="shape3cs"></div>
    </body>
</html>
{% endblock content %}

main/templates/main/experience.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            Experience and Education
        </title>
    </head>
    <body class="styles">
        <div class="container">
        <div style="text-align:center; overflow-wrap: break-word;">
            <h1 style="margin-top: 8vh; font-size: 40px;">Experience</h1>
            <h2 style="margin-top: 1vh;">Staff of Student Advocation and Welfare Department</h2>
            <h3>BEM Fakultas Ilmu Komputer Universitas Indonesia</h3>
            <h4>February 2020-now</h4>
            <h2 style="margin-top: 2vh;">Staff of Editorial Marketing</h2>
            <h3>COMPFEST</h3>
            <h4>February 2020-now</h4>
            <h2 style="margin-top: 2vh;">Mentor</h2>
            <h3>OKK UI 2020</h3>
            <h4>June 2020-September 2020</h4>
            <h2 style="margin-top: 2vh;">Staff of Relation</h2>
            <h3>Wisuda Genap 2020</h3>
            <h4>September 2020-now</h4>
        </div>
        <div style="text-align:center; overflow-wrap: break-word;">
            <h1 style="margin-top: 8vh; font-size: 40px;">Educational Background</h1>
            <h2 style="margin-top: 2vh;">Universitas Indonesia</h2>
            <h3>Information System, Faculty of Computer Science</h3>
            <h4>September 2019-2023 (expected)</h4>
            <h2 style="margin-top: 2vh;">SMA Negeri 68 Jakarta</h2>
            <h3>Natural Science</h3>
            <h4>July 2016-June 2019</h4>
            <h2 style="margin-top: 2vh;">SMP Negeri 216 Jakarta</h2>
            <h4>July 2013-June 2016</h4>
            <h2 style="margin-top: 2vh;">SDN RSBI Rawamangun 12 Pagi</h2>
            <h4 style="margin-bottom: 5vh;">July 2007-June 2013</h4>
        </div>
        </div>
        <div class="shape1ex"></div>
        <div class="shape2ex"></div>
        <div class="shape3ex"></div>
        <div class="shape4ex"></div>
        <div class="shape5ex"></div>
        <div class="shape6ex"></div>
        <div class="shape7ex"></div>
        <div class="shape8ex"></div>
    </body>
</html>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
      <title>
            Welcome!
        </title>
    </head>
    <body class="styles">
        <div class="container">
            <div class="flex-container" style="width: 100%; display: flex; float: left;">
                <div style="width: 100%; margin: auto;">
                    <h1>Hello! I am Yona</h1>
                    <h1>Nice To Meet You!</h1>
                    <div class="flex-container" style="width: 50%; display: flex; margin-left: 25%;">
                        <!-- col-centered untuk ngecenter table, dalam kasus home tombolnya mau di center-->
                        <div class="col-centered">
                            <a href="{% url 'main:aboutme' %}" class="buttons btn btn-warning" role="button"><b>Get To Know Me</b></a>
                        </div>
                        <div class="col-centered">
                            <a href="{% url 'main:works' %}" class="buttons btn btn-warning" role="button"><b>My Works</b></a>
                        </div>
                    </div>
                    <div class="flex-container" style="width: 50%; display: flex; margin-left: 25%; margin-top: 2%;">
                        <div class="col-centered">
                            <a href="{% url 'story5:courseadd' %}" class="buttons btn btn-warning" role="button"><b>Add Course to Schedule</b></a>
                        </div>
                    </div>
                    <div class="flex-container" style="width: 50%; display: flex; margin-left: 25%; margin-top: 2%;">
                        <div class="col-centered">
                            <a href="{% url 'story6:allactivities' %}" class="buttons btn btn-warning" role="button"><b>See Activities</b></a>
                        </div>
                    </div>
                </div>
                <div class="img-fluid" style="width: 100%; align-items: center; height: auto; display: block;">
                    <img src="{% static 'webcontent.png' %}" style="margin-top: 8vh;"><br/>
                </div>
        </div>
        </div>
        <div class="shape1home"></div>
        <div class="shape2home"></div>
        <div class="shape3home"></div>
    </body>
</html>

{% endblock content %}

main/templates/main/story1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story1.css' %}">
        <title>
            Welcome!
        </title>
    </head>
    <body>
        <!-- judul -->
        <h1><b>P r o f i l e</b></h1>
        <div class="container">
            <div class="flex-container" style="width: 100%; display: flex; float: left; word-wrap: break-word;">
                <div style="width: 100%; margin: auto;">
                    <p style="color:mediumblue; line-height: 180%;">
                        Nama : Herbiyona<br/>
                        Nama Panggilan : Yona<br/>
                        NPM : 1906353580<br/>
                        Angkatan : 2019<br/>
                        Hobi : Fangirling, Nonton Drama, Baca Novel, Mendengarkan Musik<br/>
                        Deskripsi : Seorang pelajar yang sedang menempuh pendidikan di jurusan Sistem Informasi<br/>dan memiliki passion di bidang menulis<br/>
                        Pendidikan Saat Ini : Universitas Indonesia<br/>
                        Riwayat Pendidikan :<br/>
                        <ul style="color:mediumblue; list-style: none; line-height: 180%;">
                            <li>Universitas Indonesia<br/></li>
                            <li>SMA Negeri 68 Jakarta<br/></li>
                            <li>SMP Negeri 216 Jakarta<br/></li>
                            <li>SDN RSBI Rawamangun 12 Pagi<br/></li>
                        </ul>
                        <ul style="color:mediumblue; list-style: none; line-height: 180%; display: inline-flex;">
                            <li><a href="https://www.linkedin.com/in/herbiyona-h-a192531b3/" target="_blank"><img src="{% static 'in.png' %}" style="max-width: 100%;"></a></li>
                            <li><a href="https://instagram.com/herbiyona_" target="_blank"><img src="{% static 'ig.png' %}" style="max-width: 100%;"></a></li>
                            <li><a href="https://twitter.com/herbiyonayon" target="_blank"><img src="{% static 'twt.png' %}" style="max-width: 100%;"></a></li>
                        </ul>
                    </p>
                </div>
                <div class="img-fluid" style="width: 100%; align-items: center; height: auto; display: block;">
                    <img src="{% static 'MY22.jpg' %}" style="max-width: 100%;"><br/>
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock content %}

main/templates/main/works.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/story3css.css' %}">
        <title>
            My Works
        </title>
    </head>
    <body class="works">
        <div class="container" style="overflow-wrap: break-word;">
        <h1 style="margin-top: 8vh;">I write, check out my works at</h1>
        <h4 style="margin-top: 4vh; margin-left: 5%;"><a class="med" href="https://medium.com/@herbiyona">https://medium.com/@herbiyona</a></h4>
        <h1 style="text-align: right;">I edit photos and videos,<br>check out some of my works</h1>
        <div class="flex-container" style="align-content: center; width: 100%; display: flex; float: left; margin-top: 8vh;">
                <div style="margin-left: auto; margin-right: auto;">
                    <img src="{% static 'ab6ixvector.jpg' %}" class="img-fluid" width="300" height="200">
                </div>
                <div style="margin-left: auto; margin-right: auto;">
                    <img src="{% static 'ab6ixvector ot5.jpg' %}" class="img-fluid" width="400" height="150">
                </div>
                <div style="margin-left: auto; margin-right: auto;">
                    <img src="{% static 'seungjoonkillthislove.jpg' %}" class="img-fluid" width="200" height="300">
                </div>
        </div>
        </div>
        <div class="shape1w"></div>
        <div class="shape2w"></div>
        <div class="shape3w"></div>
        <div class="shape4w"></div>
    </body>
</html>
{% endblock content %}